name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Node.js ${{ matrix.node-version }} / ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 22.x, 24.x]
        arch: [x64]
        include:
          # Add x86 (32-bit) tests for Windows
          - os: windows-latest
            node-version: 20.x
            arch: x86
          - os: windows-latest
            node-version: 22.x
            arch: x86

          # Add arm64 tests for macOS (Apple Silicon)
          - os: macos-latest
            node-version: 20.x
            arch: arm64
          - os: macos-latest
            node-version: 22.x
            arch: arm64
          - os: macos-latest
            node-version: 24.x
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }} (${{ matrix.arch }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.arch }}
          cache: 'npm'

      - name: Setup build tools (Windows)
        if: runner.os == 'Windows'
        run: |
          npm install --global windows-build-tools
        continue-on-error: true

      - name: Install dependencies
        run: npm ci

      - name: Build native tests
        run: npm run build
        env:
          npm_config_arch: ${{ matrix.arch }}

      - name: Run native tests
        run: npm run test

      - name: Display architecture info
        run: node -e "console.log('Node arch:', process.arch); console.log('Platform:', process.platform)"
